ALL:
	hexo clean
	hexo generate
	cp -rf public/* ../wedvefv.github.io/
	cd /Users/kunming/git/wedvefv.github.io/ &&  git add . && git commit -m "hello" && git push
s:
	hexo server
n:
	hexo new ${post}
clean:
	hexo clean
	
